### ISSUE TITLE
OnBoardingScreen

### ISSUE THREAD

**Issue by Dev-Adnani** [Dev-Adnani/Rental-App-Flutter#1]
Create A OnBoarding Screen According To Design Provided , Use Your Creativity 
For Design ...

Points : 25

**Comment by mohit-2003** [comment]
@Dev-Adnani How do I get the UI for the onboarding screen? I have not used dribble before.

**Comment by Dev-Adnani** [comment]
You Have To Make UI , Dribble Is Just For Giving How UI Will Look Like

**Comment by mohit-2003** [comment]
The name convention will also be same like this https://github.com/Dev-Adnani/MetRoom-Flutter/ project?

**Comment by mohit-2003** [comment]
Some images/graphics are needed for onboarding screen?

**Comment by Dev-Adnani** [comment]
You Can Create The Given Design Using Gradient And Text
For Naming Convention , Use That , Coz There Will Be Other Participants

**Comment by Dev-Adnani** [comment]
Hey Mohit The Design Is Pretty Simple  , Can You Improve It ?

**Comment by mohit-2003** [comment]
> Hey Mohit The Design Is Pretty Simple , Can You Improve It ?

Actually I'm not much interested in UI, others can improve it.

**Comment by Dev-Adnani** [comment]
I Can't Give Points Just For Improving Newly Created UI !
Use Any Library Like

1: flutter_onboarding_slider
2: concentric_transition
