### ISSUE TITLE
Login / SignUp Screen

### ISSUE THREAD

**Issue by Dev-Adnani** [Dev-Adnani/Rental-App-Flutter#2]
Note : We Will be Using Firebase , google json file will be provided in slack channel

Points : 75

**Comment by mohit-2003** [comment]
@Dev-Adnani I want to work on this feature, can you please assign me?

**Comment by Dev-Adnani** [comment]
Mohit Can You Complete OnBoarding First?

**Comment by mohit-2003** [comment]
> Mohit Can You Complete OnBoarding First?

Okay, assign me
